name: Coverage

on: [pull_request, push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {command: fmt, rust: nightly}
          - {command: clippy, rust: stable}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust (${{matrix.rust}})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Run cargo ${{matrix.command}}
        uses: actions-rs/cargo@v1
        with:
          command: ${{matrix.command}}
          args: "${{matrix.command == 'fmt' && '-- --check' || '-- -D warnings'}}"

  test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu, rust: stable}
          - {os: windows, rust: stable}
          - {os: macos, rust: stable}

    runs-on: ${{matrix.os}}-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust (${{matrix.rust}})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '${{matrix.rust}}'
          profile: minimal
          override: true
          components: llvm-tools-preview

      - name: Run tests
        run: cargo build

      - name: Run tests
        run: cargo test
